<?php
// Set doctype explicitly if it is not `HTML4_LOOSE`, i.e. 'HTML 4.01 Transitional'
$this->doctype('HTML5');

// Load translation data
$this->i18nTheme();

//HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
$this->js(array(
    pi::url('static/js/html5shiv.js') => array(
        'conditional' => 'lt IE 9'
    ),
    pi::url('static/js/respond.min.js') => array(
        'conditional' => 'lt IE 9'
    ),
));

// Load jQuery
$this->jquery();

// Load Bootstrap css/js and font-awesome
$this->bootstrap(array(
    'js/bootstrap.min.js',
    'font-awesome/css/font-awesome.min.css'
));

// Load front.css
$this->css($this->assetTheme('css/front.css'));

// Load localization css
$this->css($this->assetLocale('locale.css'));

// Load front.js on footer
$this->footScript()->appendFile($this->assetTheme('js/front.js'));

// Apple icons
// Apple icon for iphone
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'href'  => $this->assetTheme('image/touch-icon-iphone.png')
));
// Apple icon for ipad
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '72x72',
    'href'  => $this->assetTheme('image/touch-icon-ipad.png')
));
// Apple icon for iphone retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-iphone-retina.png')
));
// Apple icon for ipad retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-ipad-retina.png')
));

// Meta Viewport Tag
$this->headMeta('width=device-width, initial-scale=1.0', 'viewport');

// Explicitly load favicon
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/x-icon',
    'href'  => $this->favicon(),
));
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/png',
    'href'  => $this->favicon('favicon.png'),
));

// Load google analytics code
$this->ga();

// Get module name
$module = Pi::service('module')->current();

// Get navigation
$navigation = $this->nav('front');

// Get block
$blocks = $this->blocks();
$blockTemplate = $this->template('block');

// Get breadcrumbs
$breadcrumbs = $this->breadcrumb(
    array('prefix' => array(
        array(
            'label' => __('Home'),
            'href' => Pi::url($this->url('home'))
        )
    ))
);
/* End user module customize */
$platform = Pi::service('browser')->getPlatform();
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
</head>
<body id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?> pi-front <?php if (in_array($platform, array('Android', 'Ios', 'iPhone', 'iPad'))) { echo 'pi-mobile';} ?>">
<!-- Header: brand, slogan, user bar -->
<header class="pi-header">
    <div class="pi-header-user">
        <div class="container">
            <div class="row">
                <div class="col-xs-6">
                    <?php echo $this->widget('system-user-bar'); ?>
                </div>
                <div class="col-xs-6">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a class="btn btn-success" href="<?php echo Pi::url($this->url('home')); ?>guide/manage" title="ثبت باشگاه و مربی"><i class="fa fa-user"></i> ثبت باشگاه و مربی</a>
                        </li>
                        <li>
                            <?php echo $this->widget('shop-basket'); ?>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="pi-header-body">
        <div class="container">
            <div class="row">
                <div class="col-xs-4 pi-header-icon">
                    <ul>
                        <li>
                            <a href="<?php echo Pi::url($this->url('home')); ?>video/submit" title="ارسال ویدیو">
                                <img src="<?php echo $this->assetTheme('image/header-upload.png'); ?>" alt="ارسال ویدیو" class="img-responsive">
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo Pi::url($this->url('home')); ?>page/live-tv3" title="پخش زنده شبکه ۳">
                                <img src="<?php echo $this->assetTheme('image/header-live-3.png'); ?>" alt="پخش زنده شبکه ۳" class="img-responsive">
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo Pi::url($this->url('home')); ?>page/live-varzesh" title="پخش زنده شبکه ورزش">
                                <img src="<?php echo $this->assetTheme('image/header-live-varzesh.png'); ?>" alt="پخش زنده شبکه ورزش" class="img-responsive">
                            </a>
                        </li>
                        <li>
                            <a href="#" title="">
                                <img src="<?php echo $this->assetTheme('image/header-live.png'); ?>" alt="" class="img-responsive">
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-xs-5 pi-header-search">
                    <?php echo $this->widget('search-search'); ?>
                </div>
                <div class="col-xs-3 pi-header-logo">
                    <?php if ($module == 'system') { ?>
                        <h1>
                            <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>">
                                <img src="<?php echo $this->assetTheme('image/logo.png'); ?>" alt="<?php echo _escape($sitename); ?>" class="img-responsive">
                            </a>
                        </h1>
                    <?php } else { ?>
                        <h2>
                            <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>">
                                <img src="<?php echo $this->assetTheme('image/logo.png'); ?>" alt="<?php echo _escape($sitename); ?>" class="img-responsive">
                            </a>
                        </h2>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>

    <nav class="pi-header-nav">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="navbar navbar-default yamm">
                        <ul class="nav navbar-nav pi-navbar-nav">
                            <!-- Menu item -->
                            <li>
                                <a class="navbar-top-link" href="<?php echo Pi::url($this->url('home')); ?>" title="خانه">خانه</a>
                            </li>
                            <!-- Menu item -->
                            <li>
                                <a class="navbar-top-link" href="<?php echo Pi::url($this->url('home')); ?>talent" title="استعداد یابی">استعداد یابی</a>
                            </li>
                            <!-- Menu item -->
                            <li class="dropdown yamm-fw">
                                <a aria-expanded="false" href="<?php echo Pi::url($this->url('home')); ?>shop" title="فروشگاه" data-toggle="dropdown" class="navbar-top-link dropdown-toggle">فروشگاه</a>
                                <ul class="dropdown-menu hidden-xs">
                                    <li class="grid-menu grid-menu-shop">
                                        <div class="row">
                                            <div class="col-xs-3">
                                                <h4>بر اساس نوع ورزش</h4>
                                                <ul class="list-unstyled">
                                                    <li><a title="تیمی" href="<?php echo Pi::url($this->url('home')); ?>shop/team-sports">تیمی</a></li>
                                                    <li><a title="رزمی" href="<?php echo Pi::url($this->url('home')); ?>shop/martial-art">رزمی</a></li>
                                                    <li><a title="فیتنس" href="<?php echo Pi::url($this->url('home')); ?>shop/fitness">فیتنس</a></li>
                                                    <li><a title="راکتی" href="<?php echo Pi::url($this->url('home')); ?>shop/racquet-sports">راکتی</a></li>
                                                    <li><a title="اکشن" href="<?php echo Pi::url($this->url('home')); ?>shop/action">اکشن</a></li>
                                                    <li><a title="تمرکزی" href="<?php echo Pi::url($this->url('home')); ?>shop/concentration-sports">تمرکزی</a></li>
                                                    <li><a title="آبی" href="<?php echo Pi::url($this->url('home')); ?>shop/aqua-sports">آبی</a></li>
                                                    <li><a title="زمستانی" href="<?php echo Pi::url($this->url('home')); ?>shop/winter-sports">زمستانی</a></li>
                                                    <li><a title="هوای آزاد" href="<?php echo Pi::url($this->url('home')); ?>shop/outdoor-sports">هوای آزاد</a></li>
                                                    <li><a title="عمومی" href="<?php echo Pi::url($this->url('home')); ?>shop/general-sports">عمومی</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-xs-3">
                                                <h4>براساس برند</h4>
                                                <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/adidas" title="Adidas">Adidas</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/li-ning" title="LI-NING">LI-NING</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/lp-support" title="LP-SUPPORT">LP-SUPPORT</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/champex" title="Champex">Champex</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/the-north-face" title="THE NORTH FACE">THE NORTH FACE</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/president" title="President">President</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/skechers" title="SKECKERS">SKECKERS</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/under-armour" title="UNDER ARMOUR">UNDER ARMOUR</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/saucony" title="saucony">saucony</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/nike" title="NIKE">NIKE</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/reebok" title="Reebok">Reebok</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-xs-3">
                                                <h4>ورزش های پر طرفدار</h4>
                                                <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/football" title="فوتبال">فوتبال</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/boxing" title="بوکس">بوکس</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/karate" title="کاراته">کاراته</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/taekwondo" title="تکواندو">تکواندو</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/mma" title="MMA">MMA</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/jodo" title="جودو">جودو</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/fitness" title="فیتنس">فیتنس</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/basketball" title="بسکتبال">بسکتبال</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/mountaineering" title="کوهنوردی">کوهنوردی</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/tennis" title="تنیس">تنیس</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-xs-3">
                                                <h4>بر اساس نوع کالا</h4>
                                                <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/apparel" title="لباس">لباس</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/shoes" title="کفش">کفش</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/accessories" title="تجهیزات جانبی">تجهیزات جانبی</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/sport-medicine" title="علم تمرین">علم تمرین</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>shop/exciting-offer" title="پیشنهاد هیجان انگیز">پیشنهاد هیجان انگیز</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <!-- Menu item -->
                            <li class="dropdown yamm-fw">
                                <a aria-expanded="false" href="<?php echo Pi::url($this->url('home')); ?>guide" title="مربیان و باشگاه ها" data-toggle="dropdown" class="navbar-top-link dropdown-toggle">مربیان و باشگاه ها</a>
                                <ul class="dropdown-menu hidden-xs">
                                    <li class="grid-menu grid-menu-guide">
                                        <div class="row">
                                            <div class="col-xs-3">
                                                <h4>بر اساس نوع ورزش</h4>
                                                <ul class="list-unstyled">
                                                    <li><a title="تیمی" href="<?php echo Pi::url($this->url('home')); ?>guide/team-sports">تیمی</a></li>
                                                    <li><a title="رزمی" href="<?php echo Pi::url($this->url('home')); ?>guide/martial-art">رزمی</a></li>
                                                    <li><a title="فیتنس" href="<?php echo Pi::url($this->url('home')); ?>guide/fitness">فیتنس</a></li>
                                                    <li><a title="راکتی" href="<?php echo Pi::url($this->url('home')); ?>guide/racquet-sports">راکتی</a></li>
                                                    <li><a title="اکشن" href="<?php echo Pi::url($this->url('home')); ?>guide/action">اکشن</a></li>
                                                    <li><a title="تمرکزی" href="<?php echo Pi::url($this->url('home')); ?>guide/concentration-sports">تمرکزی</a></li>
                                                    <li><a title="آبی" href="<?php echo Pi::url($this->url('home')); ?>guide/aqua-sports">آبی</a></li>
                                                    <li><a title="زمستانی" href="<?php echo Pi::url($this->url('home')); ?>guide/winter-sports">زمستانی</a></li>
                                                    <li><a title="هوای آزاد" href="<?php echo Pi::url($this->url('home')); ?>guide/outdoor-sports">هوای آزاد</a></li>
                                                    <li><a title="عمومی" href="<?php echo Pi::url($this->url('home')); ?>guide/general-sports">عمومی</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-xs-3">
                                                <h4>بر اساس استان</h4>
                                                <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>guide/tehran" title="تهران">تهران</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>guide/isfahan" title="اصفهان">اصفهان</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>guide/fars" title="فارس">فارس</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>guide/alborz" title="البرز">البرز</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>guide/khorasan" title="خراسان">خراسان</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>guide/east-azarbaijan" title="آذربایجان شرقی">آذربایجان شرقی</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>guide/khuzestan" title="خوزستان">خوزستان</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>guide/yazd" title="یزد">یزد</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-xs-6 row">
                                                <h4>باشگاه ها روی نقشه</h4>
                                                <div class="clearfix">
                                                    <div class="col-xs-12">
                                                        <ul class="list-unstyled">
                                                            <li><a href="<?php echo Pi::url($this->url('home')); ?>guide/map" title="نقشه کامل تمام استان ها">نقشه کامل تمام استان ها</a></li>
                                                        </ul>
                                                    </div>
                                                    <div class="col-xs-6">
                                                        <ul class="list-unstyled">
                                                            <li><a href="<?php echo Pi::url($this->url('home')); ?>guide/map/location/1" title="استان تهران">استان تهران</a></li>
                                                            <li><a href="<?php echo Pi::url($this->url('home')); ?>guide/map/location/3" title="شهر تهران">شهر تهران</a></li>
                                                        </ul>
                                                    </div>
                                                    <div class="col-xs-6">
                                                        <ul class="list-unstyled">
                                                            <li><a href="<?php echo Pi::url($this->url('home')); ?>guide/map/location/189" title="استان اصفهان">استان اصفهان</a></li>
                                                            <li><a href="<?php echo Pi::url($this->url('home')); ?>guide/map/location/4" title="شهر اصفهان">شهر اصفهان</a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                                <h4>ورزش های پر طرفدار</h4>
                                                <div class="clearfix">
                                                    <div class="col-xs-6">
                                                        <ul class="list-unstyled">
                                                            <li><a href="<?php echo Pi::url($this->url('home')); ?>guide/football" title="فوتبال">فوتبال</a></li>
                                                            <li><a href="<?php echo Pi::url($this->url('home')); ?>guide/boxing" title="بوکس">بوکس</a></li>
                                                            <li><a href="<?php echo Pi::url($this->url('home')); ?>guide/karate" title="کاراته">کاراته</a></li>
                                                            <li><a href="<?php echo Pi::url($this->url('home')); ?>guide/taekwondo" title="تکواندو">تکواندو</a></li>
                                                            <li><a href="<?php echo Pi::url($this->url('home')); ?>guide/mma" title="MMA">MMA</a></li>
                                                        </ul>
                                                    </div>
                                                    <div class="col-xs-6">
                                                        <ul class="list-unstyled">
                                                            <li><a href="<?php echo Pi::url($this->url('home')); ?>guide/jodo" title="جودو">جودو</a></li>
                                                            <li><a href="<?php echo Pi::url($this->url('home')); ?>guide/fitness" title="فیتنس">فیتنس</a></li>
                                                            <li><a href="<?php echo Pi::url($this->url('home')); ?>guide/basketball" title="بسکتبال">بسکتبال</a></li>
                                                            <li><a href="<?php echo Pi::url($this->url('home')); ?>guide/mountaineering" title="کوهنوردی">کوهنوردی</a></li>
                                                            <li><a href="<?php echo Pi::url($this->url('home')); ?>guide/tennis" title="تنیس">تنیس</a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <!-- Menu item -->
                            <li class="dropdown yamm-fw">
                                <a aria-expanded="false" href="<?php echo Pi::url($this->url('home')); ?>video" title="ویدیو" data-toggle="dropdown" class="navbar-top-link dropdown-toggle">ویدیو</a>
                                <ul class="dropdown-menu hidden-xs">
                                    <li class="grid-menu grid-menu-video">
                                        <div class="row">
                                            <div class="col-xs-3">
                                                <h4>بر اساس نوع ورزش</h4>
                                                <ul class="list-unstyled">
                                                    <li><a title="تیمی" href="<?php echo Pi::url($this->url('home')); ?>video/team-sports">تیمی</a></li>
                                                    <li><a title="رزمی" href="<?php echo Pi::url($this->url('home')); ?>video/martial-art">رزمی</a></li>
                                                    <li><a title="فیتنس" href="<?php echo Pi::url($this->url('home')); ?>video/fitness">فیتنس</a></li>
                                                    <li><a title="راکتی" href="<?php echo Pi::url($this->url('home')); ?>video/racquet-sports">راکتی</a></li>
                                                    <li><a title="اکشن" href="<?php echo Pi::url($this->url('home')); ?>video/action">اکشن</a></li>
                                                    <li><a title="تمرکزی" href="<?php echo Pi::url($this->url('home')); ?>video/concentration-sports">تمرکزی</a></li>
                                                    <li><a title="آبی" href="<?php echo Pi::url($this->url('home')); ?>video/aqua-sports">آبی</a></li>
                                                    <li><a title="زمستانی" href="<?php echo Pi::url($this->url('home')); ?>video/winter-sports">زمستانی</a></li>
                                                    <li><a title="هوای آزاد" href="<?php echo Pi::url($this->url('home')); ?>video/outdoor-sports">هوای آزاد</a></li>
                                                    <li><a title="عمومی" href="<?php echo Pi::url($this->url('home')); ?>video/general-sports">عمومی</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-xs-3">
                                                <h4>بر اساس موضوع</h4>
                                                <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>video/training" title="آموزشی">آموزشی</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>video/motivational" title="انگیزشی">انگیزشی</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>video/professionals" title="حرفه ای ها">حرفه ای ها</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>video/biography" title="بیوگرافی">بیوگرافی</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>video/sport-fun" title="طنز">طنز</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>video/sport-animation" title="انیمیشن">انیمیشن</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>video/challenges-and-competitions" title="مسابقات و چالش ها">مسابقات و چالش ها</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>video/sport-technology-brands" title="تکنولوژی ورزشی/برندها">تکنولوژی ورزشی/برندها</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-xs-6 row">
                                                <h4>ورزش های پر طرفدار</h4>
                                                <div class="col-xs-6">
                                                    <ul class="list-unstyled">
                                                        <li><a href="<?php echo Pi::url($this->url('home')); ?>video/exciting-sport-ability-challenge" title="عجیب ترین توانایی ورزشی">عجیب ترین توانایی ورزشی</a></li>
                                                        <li><a href="<?php echo Pi::url($this->url('home')); ?>video/break-dance" title="ایروبیک حرفه ای">ایروبیک حرفه ای</a></li>
                                                        <li><a href="<?php echo Pi::url($this->url('home')); ?>video/football" title="فوتبال">فوتبال</a></li>
                                                        <li><a href="<?php echo Pi::url($this->url('home')); ?>video/boxing" title="بوکس">بوکس</a></li>
                                                        <li><a href="<?php echo Pi::url($this->url('home')); ?>video/karate" title="کاراته">کاراته</a></li>
                                                        <li><a href="<?php echo Pi::url($this->url('home')); ?>video/taekwondo" title="تکواندو">تکواندو</a></li>
                                                    </ul>
                                                </div>
                                                <div class="col-xs-6">
                                                    <ul class="list-unstyled">
                                                        <li><a href="<?php echo Pi::url($this->url('home')); ?>video/mma" title="MMA">MMA</a></li>
                                                        <li><a href="<?php echo Pi::url($this->url('home')); ?>video/jodo" title="جودو">جودو</a></li>
                                                        <li><a href="<?php echo Pi::url($this->url('home')); ?>video/fitness" title="فیتنس">فیتنس</a></li>
                                                        <li><a href="<?php echo Pi::url($this->url('home')); ?>video/basketball" title="بسکتبال">بسکتبال</a></li>
                                                        <li><a href="<?php echo Pi::url($this->url('home')); ?>video/mountaineering" title="کوهنوردی">کوهنوردی</a></li>
                                                        <li><a href="<?php echo Pi::url($this->url('home')); ?>video/tennis" title="تنیس">تنیس</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <!-- Menu item -->
                            <li class="dropdown yamm-fw">
                                <a aria-expanded="false" href="<?php echo Pi::url($this->url('home')); ?>event" title="تورها و بلیط ها" data-toggle="dropdown" class="navbar-top-link dropdown-toggle">تورها و بلیط ها</a>
                                <ul class="dropdown-menu hidden-xs">
                                    <li class="grid-menu grid-menu-event">
                                        <div class="row">
                                            <div class="col-xs-6">
                                                <h4>بلیط اماکن ورزشی</h4>
                                                <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>event/tickets-to-sporting-venues" title="همه بلیط اماکن ورزشی">همه بلیط اماکن ورزشی</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>event/swimming-pool" title="استخر">استخر</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>event/" title="بدنسازی">بدنسازی</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>event/jumping" title="جامپینگ">جامپینگ</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>event/paintball" title="پینت بال">پینت بال</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>event/carting" title="کارتینگ">کارتینگ</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>event/rafting" title="صخره نوردی">صخره نوردی</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>event" title="سایر">سایر</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-xs-6">
                                                <h4>تورهای ورزشی</h4>
                                                <ul class="list-unstyled">
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>event/sport-tours" title="همه تورهای ورزشی">همه تورهای ورزشی</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>event/ecotourism-tour" title="تور طبیعت گردی">تور طبیعت گردی</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>event/mountain-climbing-tour" title="تور کوهنوردی">تور کوهنوردی</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>event/exciting-tours" title="تور هیجان انگیز">تور هیجان انگیز</a></li>
                                                    <li><a href="<?php echo Pi::url($this->url('home')); ?>event" title="تور دوچرخه سواری">تور دوچرخه سواری</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <!-- Menu item -->
                            <li class="dropdown yamm-fw">
                                <a aria-expanded="false" href="<?php echo Pi::url($this->url('home')); ?>video/challenges-and-competitions" title="مسابقات و چالش ها" data-toggle="dropdown" class="navbar-top-link dropdown-toggle">مسابقات و چالش ها</a>
                                <ul class="dropdown-menu hidden-xs">
                                    <li class="grid-menu">
                                        <div class="row">
                                            <div class="col-xs-4">
                                                <h4>چالش ها و مسابقات برگزار شده</h4>
                                                <a title="چالش ها و مسابقات برگزار شده" href="<?php echo Pi::url($this->url('home')); ?>video/performed-challenge-or-competition" class="text-center">
                                                    <img class="img-responsive img-rounded" src="<?php echo Pi::url($this->url('home')); ?>upload/image/menu/challengesbargozar-shode.jpg" alt="چالش ها و مسابقات برگزار شده">
                                                </a>
                                            </div>
                                            <div class="col-xs-4">
                                                <h4>چالش یا مسابقه درحال برگزاری</h4>
                                                <a title="چالش یا مسابقه درحال برگزاری" href="<?php echo Pi::url($this->url('home')); ?>video/on-performing-challenge-or-competition" class="text-center">
                                                    <img class="img-responsive img-rounded" src="<?php echo Pi::url($this->url('home')); ?>upload/image/menu/challenges-dar-hale-bargozari.jpg" alt="چالش یا مسابقه درحال برگزاری">
                                                </a>
                                            </div>
                                            <div class="col-xs-4">
                                                <h4>چالش یا مسابقه بعدی</h4>
                                                <a title="چالش یا مسابقه بعدی" href="<?php echo Pi::url($this->url('home')); ?>video/next-challenge-or-competition" class="text-center">
                                                    <img class="img-responsive img-rounded" src="<?php echo Pi::url($this->url('home')); ?>upload/image/menu/challenges-ayande.jpg" alt="چالش یا مسابقه بعدی">
                                                </a>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <!-- Menu item -->
                            <li class="dropdown yamm-fw">
                                <a aria-expanded="false" href="<?php echo Pi::url($this->url('home')); ?>news" title="علم ورزش" data-toggle="dropdown" class="navbar-top-link dropdown-toggle">علم ورزش</a>
                                <ul class="dropdown-menu hidden-xs">
                                    <li class="grid-menu">
                                        <div class="row">
                                            <div class="col-xs-3">
                                                <h4>علم تمرین</h4>
                                                <a title="علم تمرین" href="<?php echo Pi::url($this->url('home')); ?>news/sports-medicine" class="text-center">
                                                    <img class="img-responsive img-rounded" src="<?php echo Pi::url($this->url('home')); ?>upload/image/menu/sports-medicine.jpg" alt="علم تمرین">
                                                </a>
                                            </div>
                                            <div class="col-xs-3">
                                                <h4>معرفی ورزشکاران</h4>
                                                <a title="معرفی ورزشکاران" href="<?php echo Pi::url($this->url('home')); ?>news/introduction-athletes" class="text-center">
                                                    <img class="img-responsive img-rounded" src="<?php echo Pi::url($this->url('home')); ?>upload/image/menu/introduction-athletes.jpg" alt="معرفی ورزشکاران">
                                                </a>
                                            </div>
                                            <div class="col-xs-3">
                                                <h4>مدیریت در ورزش</h4>
                                                <a title="مدیریت در ورزش" href="<?php echo Pi::url($this->url('home')); ?>news/sports-management" class="text-center">
                                                    <img class="img-responsive img-rounded" src="<?php echo Pi::url($this->url('home')); ?>upload/image/menu/sports-management.jpg" alt="مدیریت در ورزش">
                                                </a>
                                            </div>
                                            <div class="col-xs-3">
                                                <h4>تغذیه و رژیم</h4>
                                                <a title="تغذیه و رژیم" href="<?php echo Pi::url($this->url('home')); ?>news/nutrition-and-dietetics" class="text-center">
                                                    <img class="img-responsive img-rounded" src="<?php echo Pi::url($this->url('home')); ?>upload/image/menu/nutrition-and-dietetics.jpg" alt="تغذیه و رژیم">
                                                </a>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>
<!-- Page main content: breadcrumb, flash-messenger, blocks and module content -->
<section class="pi-section">
    <div class="container">
        <div class="pi-main-container">
            <?php if ($breadcrumbs) { echo $breadcrumbs; } ?>
            <!-- Flash messenger -->
            <?php include $this->template('flash-messenger'); ?>
            <!-- Top head zone -->
            <?php if (!empty($blocks['0']) && isset($blocks['99'])) { ?>
                <div class="row">
                    <?php if (!empty($blocks['0'])) { ?>
                        <div class="pi-zone-0 col-xs-8">
                            <?php foreach ($blocks['0'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                    <!-- Bottom foot zone -->
                    <?php if (isset($blocks['99'])) { ?>
                        <div class="pi-zone-99 col-xs-4">
                            <?php foreach ($blocks['99'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                </div>
            <?php } ?>

            <!-- Center bottom zone -->
            <?php if (isset($blocks['7'])) { ?>
                <div class="row">
                    <div class="pi-zone-7 col-xs-12">
                        <?php foreach ($blocks['7'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                </div>
            <?php } ?>
            <div class="row">
                <!-- Left zone -->
                <?php if (!empty($blocks['1'])) { ?>
                    <div class="pi-zone-1 col-xs-4">
                        <?php foreach ($blocks['1'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
                <div class="<?php
                if (isset($blocks['1']) && isset($blocks['8'])) {
                    echo 'col-xs-4';
                } elseif (isset($blocks['1']) || isset($blocks['8'])) {
                    echo 'col-xs-8';
                } else {
                    echo 'col-xs-12';
                }
                ?>">
                    <!-- Center top zone -->
                    <?php if (isset($blocks['2'])) { ?>
                        <div class="pi-zone-2">
                            <?php foreach ($blocks['2'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                    <?php if (isset($blocks['3']) || isset($blocks['4'])) { ?>
                        <div class="row">
                            <div class="col-xs-6 pi-zone-3">
                                <?php
                                if (isset($blocks['3'])) {
                                    foreach ($blocks['3'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                            <div class="col-xs-6 pi-zone-4">
                                <?php
                                if (isset($blocks['4'])) {
                                    foreach ($blocks['4'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                        </div>
                    <?php } ?>
                    <!-- Module content starts -->
                    <?php if (!empty($content)) { ?>
                        <div class="<?php echo $module; ?>">
                            <div class="pi-module-content" ng-app="<?php echo $module; ?>">
                                <?php echo $content; ?>
                            </div>
                            <?php echo Pi::service('comment')->load(array('options' => array('type' => 'js'))); ?>
                        </div>
                    <?php } ?>
                    <!-- Module content ends -->
                    <?php if (isset($blocks['5']) || isset($blocks['6'])) { ?>
                        <div class="row">
                            <div class="col-xs-6 pi-zone-5">
                                <?php
                                if (isset($blocks['5'])) {
                                    foreach ($blocks['5'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                            <div class="col-xs-6 pi-zone-6">
                                <?php
                                if (isset($blocks['6'])) {
                                    foreach ($blocks['6'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                        </div>
                    <?php } ?>
                </div>
                <!-- Right zone -->
                <?php if (isset($blocks['8'])) { ?>
                    <div class="col-xs-4 pi-zone-8">
                        <?php foreach ($blocks['8'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</section>
<!-- Footer: sitelink -->
<footer class="pi-footer">
    <div class="pi-footer-app">
        <div class="container">
            <div class="row">
                <div class="col-xs-6 pi-footer-app-banner">
                    <img src="<?php echo $this->assetTheme('image/footer-app.png') ?>" alt="" class="img-responsive">
                </div>
                <div class="col-xs-2 pi-footer-app-logo">
                    <p>
                        <img src="<?php echo $this->assetTheme('image/app-android.png') ?>" alt="" class="img-responsive">
                    </p>
                    <p>
                        <img src="<?php echo $this->assetTheme('image/app-ios.png') ?>" alt="" class="img-responsive">
                    </p>
                </div>
                <div class="col-xs-4 pi-footer-main-logo">
                    <img src="<?php echo $this->assetTheme('image/footer-logo.png') ?>" alt="" class="img-responsive">
                </div>
            </div>
        </div>
    </div>
    <div class="pi-footer-body clearfix">
        <div class="container">
            <div class="row">
                <div class="clearfix">
                    <div class="col-xs-3">
                        <h2>درباره <?php echo _escape($sitename); ?></h2>
                        <p>آنلاین اسپرت،<strong><a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>"><?php echo _escape($sitename); ?></a></strong> ایران است که به صورت تخصصی به موضوع ورزش در رشته های مختلف میپردازد.این سامانه بر آن است تا مرجعی برای تمامی ورزشکاران و ورزش دوستان باشد.</p>
                        <div class="clearfix">
                            <div class="col-xs-6">
                                <img class="img-responsive" src="<?php echo $this->assetTheme('image/behpardakht.png'); ?>" alt="به پرداخت">
                            </div>
                            <div class="col-xs-6">
                                <img id="drftbrgwrgvlbrgwrgvl" class="img-responsive" onclick='window.open("http://trustseal.enamad.ir/Verify.aspx?id=16565&p=nbpdhwmbyncrhwmbyncr", "Popup","toolbar=no, location=no, statusbar=no, menubar=no, scrollbars=1, resizable=0, width=580, height=600, top=30")' alt="نماد اعتماد الکترونیک" src="http://trustseal.enamad.ir/logo.aspx?id=16565&p=lznbkzoefujykzoefujy" />
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-9">
                        <div class="col-xs-3">
                            <h4>فروشگاه ورزشی</h4>
                            <ul class="list-unstyled">
                                <li><a title="تیمی" href="<?php echo Pi::url($this->url('home')); ?>shop/team-sports"><i class="fa fa-angle-left"></i> محصولات تیمی</a></li>
                                <li><a title="رزمی" href="<?php echo Pi::url($this->url('home')); ?>shop/martial-art"><i class="fa fa-angle-left"></i> محصولات رزمی</a></li>
                                <li><a title="فیتنس" href="<?php echo Pi::url($this->url('home')); ?>shop/fitness"><i class="fa fa-angle-left"></i> محصولات فیتنس</a></li>
                                <li><a title="راکتی" href="<?php echo Pi::url($this->url('home')); ?>shop/racquet-sports"><i class="fa fa-angle-left"></i> محصولات راکتی</a></li>
                                <li><a title="اکشن" href="<?php echo Pi::url($this->url('home')); ?>shop/action"><i class="fa fa-angle-left"></i> محصولات اکشن</a></li>
                                <li><a title="تمرکزی" href="<?php echo Pi::url($this->url('home')); ?>shop/concentration-sports"><i class="fa fa-angle-left"></i> محصولات تمرکزی</a></li>
                                <li><a title="آبی" href="<?php echo Pi::url($this->url('home')); ?>shop/aqua-sports"><i class="fa fa-angle-left"></i> محصولات آبی</a></li>
                                <li><a title="زمستانی" href="<?php echo Pi::url($this->url('home')); ?>shop/winter-sports"><i class="fa fa-angle-left"></i> محصولات زمستانی</a></li>
                                <li><a title="هوای آزاد" href="<?php echo Pi::url($this->url('home')); ?>shop/outdoor-sports"><i class="fa fa-angle-left"></i> محصولات هوای آزاد</a></li>
                                <li><a title="عمومی" href="<?php echo Pi::url($this->url('home')); ?>shop/general-sports"><i class="fa fa-angle-left"></i> محصولات عمومی</a></li>
                            </ul>
                        </div>
                        <div class="col-xs-3">
                            <h4>مربیان و باشگاه های ورزشی</h4>
                            <ul class="list-unstyled">
                                <li><a title="تیمی" href="<?php echo Pi::url($this->url('home')); ?>guide/team-sports"><i class="fa fa-angle-left"></i> مربیان و باشگاه های تیمی</a></li>
                                <li><a title="رزمی" href="<?php echo Pi::url($this->url('home')); ?>guide/martial-art"><i class="fa fa-angle-left"></i> مربیان و باشگاه های رزمی</a></li>
                                <li><a title="فیتنس" href="<?php echo Pi::url($this->url('home')); ?>guide/fitness"><i class="fa fa-angle-left"></i> مربیان و باشگاه های فیتنس</a></li>
                                <li><a title="راکتی" href="<?php echo Pi::url($this->url('home')); ?>guide/racquet-sports"><i class="fa fa-angle-left"></i> مربیان و باشگاه های راکتی</a></li>
                                <li><a title="اکشن" href="<?php echo Pi::url($this->url('home')); ?>guide/action"><i class="fa fa-angle-left"></i> مربیان و باشگاه های اکشن</a></li>
                                <li><a title="تمرکزی" href="<?php echo Pi::url($this->url('home')); ?>guide/concentration-sports"><i class="fa fa-angle-left"></i> مربیان و باشگاه های تمرکزی</a></li>
                                <li><a title="آبی" href="<?php echo Pi::url($this->url('home')); ?>guide/aqua-sports"><i class="fa fa-angle-left"></i> مربیان و باشگاه های آبی</a></li>
                                <li><a title="زمستانی" href="<?php echo Pi::url($this->url('home')); ?>guide/winter-sports"><i class="fa fa-angle-left"></i> مربیان و باشگاه های زمستانی</a></li>
                                <li><a title="هوای آزاد" href="<?php echo Pi::url($this->url('home')); ?>guide/outdoor-sports"><i class="fa fa-angle-left"></i> مربیان و باشگاه های هوای آزاد</a></li>
                                <li><a title="عمومی" href="<?php echo Pi::url($this->url('home')); ?>guide/general-sports"><i class="fa fa-angle-left"></i> مربیان و باشگاه های عمومی</a></li>
                            </ul>
                        </div>
                        <div class="col-xs-3">
                            <h4>ویدیو های ورزشی</h4>
                            <ul class="list-unstyled">
                                <li><a title="تیمی" href="<?php echo Pi::url($this->url('home')); ?>video/team-sports"><i class="fa fa-angle-left"></i> ویدیو های تیمی</a></li>
                                <li><a title="رزمی" href="<?php echo Pi::url($this->url('home')); ?>video/martial-art"><i class="fa fa-angle-left"></i> ویدیو های رزمی</a></li>
                                <li><a title="فیتنس" href="<?php echo Pi::url($this->url('home')); ?>video/fitness"><i class="fa fa-angle-left"></i> ویدیو های فیتنس</a></li>
                                <li><a title="راکتی" href="<?php echo Pi::url($this->url('home')); ?>video/racquet-sports"><i class="fa fa-angle-left"></i> ویدیو های راکتی</a></li>
                                <li><a title="اکشن" href="<?php echo Pi::url($this->url('home')); ?>video/action"><i class="fa fa-angle-left"></i> ویدیو های اکشن</a></li>
                                <li><a title="تمرکزی" href="<?php echo Pi::url($this->url('home')); ?>video/concentration-sports"><i class="fa fa-angle-left"></i> ویدیو های تمرکزی</a></li>
                                <li><a title="آبی" href="<?php echo Pi::url($this->url('home')); ?>video/aqua-sports"><i class="fa fa-angle-left"></i> ویدیو های آبی</a></li>
                                <li><a title="زمستانی" href="<?php echo Pi::url($this->url('home')); ?>video/winter-sports"><i class="fa fa-angle-left"></i> ویدیو های زمستانی</a></li>
                                <li><a title="هوای آزاد" href="<?php echo Pi::url($this->url('home')); ?>video/outdoor-sports"><i class="fa fa-angle-left"></i> ویدیو های هوای آزاد</a></li>
                                <li><a title="عمومی" href="<?php echo Pi::url($this->url('home')); ?>video/general-sports"><i class="fa fa-angle-left"></i> ویدیو های عمومی</a></li>
                            </ul>
                        </div>
                        <div class="col-xs-3">
                            <h4>سایر بخش های ورزشی</h4>
                            <ul class="list-unstyled">
                                <li><a title="استعدادیابی آنلاین" href="<?php echo Pi::url($this->url('home')); ?>talent"><i class="fa fa-angle-left"></i> استعدادیابی آنلاین</a></li>
                                <li><a title="مسابقات و چالش ها" href="<?php echo Pi::url($this->url('home')); ?>news/competitions-and-challenges"><i class="fa fa-angle-left"></i> مسابقات و چالش ها</a></li>
                                <li><a title="علم ورزش" href="<?php echo Pi::url($this->url('home')); ?>news"><i class="fa fa-angle-left"></i> علم ورزش</a></li>
                                <li><a title="قوانین و مقررات" href="<?php echo Pi::url($this->url('home')); ?>page/terms-and-conditions"><i class="fa fa-angle-left"></i> قوانین و مقررات</a></li>
                                <li><a title="راهنمای خرید و ارسال" href="<?php echo Pi::url($this->url('home')); ?>page/help"><i class="fa fa-angle-left"></i> راهنمای خرید و ارسال</a></li>
                                <li><a title="تبلیغات" href="<?php echo Pi::url($this->url('home')); ?>page/ads"><i class="fa fa-angle-left"></i> تبلیغات</a></li>
                                <li><a title="درباره ما" href="<?php echo Pi::url($this->url('home')); ?>page/about-us"><i class="fa fa-angle-left"></i> درباره ما</a></li>
                                <li><a title="تماس با ما" href="<?php echo Pi::url($this->url('home')); ?>contact"><i class="fa fa-angle-left"></i> تماس با ما</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="pi-footer-copyright clearfix">
        <div class="container">
            <div class="row">
                <div class="text-left col-xs-6" data-rel="license">تمام حقوق مطالب برای وب سایت <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>"><?php echo _escape($sitename); ?></a> محفوظ است.</div>
                <div class="text-right col-xs-6" data-rel="license">طراحی و توسعه <a title="فراگسترش" href="http://www.faragostaresh.com" target="_blank">فراگسترش</a></div>
            </div>
        </div>
    </div>
</footer>
<section class="pi-side-network">
    <ul>
        <li>
            <a href="https://www.instagram.com/osport.ir" title="">
                <img src="<?php echo $this->assetTheme('image/social-1.png') ?>" alt="اینستاگرام" class="img-responsive">
            </a>
        </li>
        <li>
            <a href="https://www.telegram.me/osportir" title="">
                <img src="<?php echo $this->assetTheme('image/social-2.png') ?>" alt="تلگرام" class="img-responsive">
            </a>
        </li>
        <li>
            <a href="https://www.linkedin.com/in/osport-ir-782588117" title="">
                <img src="<?php echo $this->assetTheme('image/social-3.png') ?>" alt=""لینکد ان class="img-responsive">
            </a>
        </li>
        <li>
            <a href="https://www.facebook.com/Osport-1424533724434821" title="">
                <img src="<?php echo $this->assetTheme('image/social-4.png') ?>" alt="فیسبوک" class="img-responsive">
            </a>
        </li>
        <li>
            <a href="http://www.aparat.com/osport.ir" title="">
                <img src="<?php echo $this->assetTheme('image/social-5.png') ?>" alt="آپارات" class="img-responsive">
            </a>
        </li>
    </ul>
</section>
</body>
</html>