<?php
// Set doctype explicitly if it is not `HTML4_LOOSE`, i.e. 'HTML 4.01 Transitional'
$this->doctype('HTML5');

// Load translation data
$this->i18nTheme();

//HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
$this->js(array(
    pi::url('static/js/html5shiv.js') => array(
        'conditional' => 'lt IE 9'
    ),
    pi::url('static/js/respond.min.js') => array(
        'conditional' => 'lt IE 9'
    ),
));

// Load jQuery
$this->jquery();

// Load Bootstrap css/js and font-awesome
$this->bootstrap(array(
    'js/bootstrap.min.js',
    'font-awesome/css/font-awesome.min.css'
));

// Load front.css
$this->css($this->assetTheme('css/front.css'));

// Load localization css
$this->css($this->assetLocale('locale.css'));

// Load front.js on footer
$this->footScript()->appendFile($this->assetTheme('js/front.js'));

// Apple icons
// Apple icon for iphone
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'href'  => $this->assetTheme('image/touch-icon-iphone.png')
));
// Apple icon for ipad
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '72x72',
    'href'  => $this->assetTheme('image/touch-icon-ipad.png')
));
// Apple icon for iphone retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-iphone-retina.png')
));
// Apple icon for ipad retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-ipad-retina.png')
));

// Meta Viewport Tag
$this->headMeta('width=device-width, initial-scale=1.0', 'viewport');

// Explicitly load favicon
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/x-icon',
    'href'  => $this->favicon(),
));
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/png',
    'href'  => $this->favicon('favicon.png'),
));

// Load google analytics code
$this->ga();

// Get module name
$module = Pi::service('module')->current();

// Get navigation
$navigation = $this->nav('front');

// Get block
$blocks = $this->blocks();
$blockTemplate = $this->template('block');

// Get breadcrumbs
$breadcrumbs = $this->breadcrumb(
    array('prefix' => array(
        array(
            'label' => __('Home'),
            'href' => Pi::url($this->url('home'))
        )
    ))
);
/* End user module customize */
$platform = Pi::service('browser')->getPlatform();
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
</head>
<body id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?> pi-front <?php if (in_array($platform, array('Android', 'Ios', 'iPhone', 'iPad'))) { echo 'pi-mobile';} ?>">
<!-- Header: brand, slogan, user bar -->
<header class="pi-header">
    <div class="pi-header-user">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <?php echo $this->widget('system-user-bar'); ?>
                </div>
            </div>
        </div>
    </div>
    <div class="pi-header-body">
        <div class="container">
            <div class="row">
                <div class="col-xs-4 pi-header-icon">
                    <ul>
                        <li>
                            <a href="#" title="">
                                <img src="<?php echo $this->assetTheme('image/header-upload.png'); ?>" alt="" class="img-responsive">
                            </a>
                        </li>
                        <li>
                            <a href="#" title="">
                                <img src="<?php echo $this->assetTheme('image/header-live-3.png'); ?>" alt="" class="img-responsive">
                            </a>
                        </li>
                        <li>
                            <a href="#" title="">
                                <img src="<?php echo $this->assetTheme('image/header-live-varzesh.png'); ?>" alt="" class="img-responsive">
                            </a>
                        </li>
                        <li>
                            <a href="#" title="">
                                <img src="<?php echo $this->assetTheme('image/header-live.png'); ?>" alt="" class="img-responsive">
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-xs-5 pi-header-search">
                    <?php echo $this->widget('search-search'); ?>
                </div>
                <div class="col-xs-3 pi-header-logo">
                    <?php if ($module == 'system') { ?>
                        <h1>
                            <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>">
                                <img src="<?php echo $this->assetTheme('image/logo.png'); ?>" alt="<?php echo _escape($sitename); ?>" class="img-responsive">
                            </a>
                        </h1>
                    <?php } else { ?>
                        <h2>
                            <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>">
                                <img src="<?php echo $this->assetTheme('image/logo.png'); ?>" alt="<?php echo _escape($sitename); ?>" class="img-responsive">
                            </a>
                        </h2>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="navbar-header">
                        <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <i class="fa fa-bars"></i>
                        </button>
                    </div>
                    <div class="navbar-collapse collapse">
                        <?php echo $navigation->menu()->setUlClass('nav navbar-nav pi-navbar-nav'); ?>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>
<!-- Page main content: breadcrumb, flash-messenger, blocks and module content -->
<section class="pi-section">
    <div class="container">
        <div class="pi-main-container">
            <?php if ($breadcrumbs) { echo $breadcrumbs; } ?>
            <!-- Flash messenger -->
            <?php include $this->template('flash-messenger'); ?>
            <!-- Top head zone -->
            <?php if (!empty($blocks['0']) && isset($blocks['99'])) { ?>
                <div class="row">
                    <?php if (!empty($blocks['0'])) { ?>
                        <div class="pi-zone-0 col-xs-8">
                            <?php foreach ($blocks['0'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                    <!-- Bottom foot zone -->
                    <?php if (isset($blocks['99'])) { ?>
                        <div class="pi-zone-99 col-xs-4">
                            <?php foreach ($blocks['99'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                </div>
            <?php } ?>

            <!-- Center bottom zone -->
            <?php if (isset($blocks['7'])) { ?>
                <div class="row">
                    <div class="pi-zone-7 col-xs-12">
                        <?php foreach ($blocks['7'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                </div>
            <?php } ?>
            <div class="row">
                <!-- Left zone -->
                <?php if (!empty($blocks['1'])) { ?>
                    <div class="pi-zone-1 col-xs-4">
                        <?php foreach ($blocks['1'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
                <div class="<?php
                if (isset($blocks['1']) && isset($blocks['8'])) {
                    echo 'col-xs-4';
                } elseif (isset($blocks['1']) || isset($blocks['8'])) {
                    echo 'col-xs-8';
                } else {
                    echo 'col-xs-12';
                }
                ?>">
                    <!-- Center top zone -->
                    <?php if (isset($blocks['2'])) { ?>
                        <div class="pi-zone-2">
                            <?php foreach ($blocks['2'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                    <?php if (isset($blocks['3']) || isset($blocks['4'])) { ?>
                        <div class="row">
                            <div class="col-xs-6 pi-zone-3">
                                <?php
                                if (isset($blocks['3'])) {
                                    foreach ($blocks['3'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                            <div class="col-xs-6 pi-zone-4">
                                <?php
                                if (isset($blocks['4'])) {
                                    foreach ($blocks['4'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                        </div>
                    <?php } ?>
                    <!-- Module content starts -->
                    <?php if (!empty($content)) { ?>
                        <div class="<?php echo $module; ?>">
                            <div class="pi-module-content" ng-app="<?php echo $module; ?>">
                                <?php echo $content; ?>
                            </div>
                            <?php echo Pi::service('comment')->load(array('options' => array('type' => 'js'))); ?>
                        </div>
                    <?php } ?>
                    <!-- Module content ends -->
                    <?php if (isset($blocks['5']) || isset($blocks['6'])) { ?>
                        <div class="row">
                            <div class="col-xs-6 pi-zone-5">
                                <?php
                                if (isset($blocks['5'])) {
                                    foreach ($blocks['5'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                            <div class="col-xs-6 pi-zone-6">
                                <?php
                                if (isset($blocks['6'])) {
                                    foreach ($blocks['6'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                        </div>
                    <?php } ?>
                </div>
                <!-- Right zone -->
                <?php if (isset($blocks['8'])) { ?>
                    <div class="col-xs-4 pi-zone-8">
                        <?php foreach ($blocks['8'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</section>
<!-- Footer: sitelink -->
<footer class="pi-footer">
    <div class="pi-footer-app">
        <div class="container">
            <div class="row">
                <div class="col-xs-6 pi-footer-app-banner">
                    <img src="<?php echo $this->assetTheme('image/footer-app.png') ?>" alt="" class="img-responsive">
                </div>
                <div class="col-xs-2 pi-footer-app-logo">
                    <p>
                        <img src="<?php echo $this->assetTheme('image/app-android.png') ?>" alt="" class="img-responsive">
                    </p>
                    <p>
                        <img src="<?php echo $this->assetTheme('image/app-ios.png') ?>" alt="" class="img-responsive">
                    </p>
                </div>
                <div class="col-xs-4 pi-footer-main-logo">
                    <img src="<?php echo $this->assetTheme('image/footer-logo.png') ?>" alt="" class="img-responsive">
                </div>
            </div>
        </div>
    </div>
    <div class="pi-footer-body clearfix">
        <div class="container">
            <div class="row">
                <div class="clearfix">
                    <div class="col-xs-3">
                        <h2>درباره <?php echo _escape($sitename); ?></h2>
                        <p>آنلاین اسپرت،<strong><a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>"><?php echo _escape($sitename); ?></a></strong> ایران است که به صورت تخصصی به موضوع ورزش در رشته های مختلف میپردازد.این سامانه بر آن است تا مرجعی برای تمامی ورزشکاران و ورزش دوستان باشد.</p>
                        <div class="clearfix">
                            <div class="col-xs-6">
                                <img class="img-responsive" src="<?php echo $this->assetTheme('image/behpardakht.png'); ?>" alt="به پرداخت">
                            </div>
                            <div class="col-xs-6">
                                <img id="drftbrgwrgvlbrgwrgvl" class="img-responsive" onclick='window.open("http://trustseal.enamad.ir/Verify.aspx?id=16565&p=nbpdhwmbyncrhwmbyncr", "Popup","toolbar=no, location=no, statusbar=no, menubar=no, scrollbars=1, resizable=0, width=580, height=600, top=30")' alt="نماد اعتماد الکترونیک" src="http://trustseal.enamad.ir/logo.aspx?id=16565&p=lznbkzoefujykzoefujy" />
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-9">
                        <div class="col-xs-3">
                            <h4>فروشگاه ورزشی</h4>
                            <ul class="list-unstyled">
                                <li><a title="تیمی" href="<?php echo Pi::url($this->url('home')); ?>shop/team-sports"><i class="fa fa-angle-left"></i> محصولات تیمی</a></li>
                                <li><a title="رزمی" href="<?php echo Pi::url($this->url('home')); ?>shop/martial-art"><i class="fa fa-angle-left"></i> محصولات رزمی</a></li>
                                <li><a title="فیتنس" href="<?php echo Pi::url($this->url('home')); ?>shop/fitness"><i class="fa fa-angle-left"></i> محصولات فیتنس</a></li>
                                <li><a title="راکتی" href="<?php echo Pi::url($this->url('home')); ?>shop/racquet-sports"><i class="fa fa-angle-left"></i> محصولات راکتی</a></li>
                                <li><a title="اکشن" href="<?php echo Pi::url($this->url('home')); ?>shop/action"><i class="fa fa-angle-left"></i> محصولات اکشن</a></li>
                                <li><a title="تمرکزی" href="<?php echo Pi::url($this->url('home')); ?>shop/concentration-sports"><i class="fa fa-angle-left"></i> محصولات تمرکزی</a></li>
                                <li><a title="آبی" href="<?php echo Pi::url($this->url('home')); ?>shop/aqua-sports"><i class="fa fa-angle-left"></i> محصولات آبی</a></li>
                                <li><a title="زمستانی" href="<?php echo Pi::url($this->url('home')); ?>shop/winter-sports"><i class="fa fa-angle-left"></i> محصولات زمستانی</a></li>
                                <li><a title="هوای آزاد" href="<?php echo Pi::url($this->url('home')); ?>shop/outdoor-sports"><i class="fa fa-angle-left"></i> محصولات هوای آزاد</a></li>
                                <li><a title="عمومی" href="<?php echo Pi::url($this->url('home')); ?>shop/general-sports"><i class="fa fa-angle-left"></i> محصولات عمومی</a></li>
                            </ul>
                        </div>
                        <div class="col-xs-3">
                            <h4>مربیان و باشگاه های ورزشی</h4>
                            <ul class="list-unstyled">
                                <li><a title="تیمی" href="<?php echo Pi::url($this->url('home')); ?>guide/team-sports"><i class="fa fa-angle-left"></i> مربیان و باشگاه های تیمی</a></li>
                                <li><a title="رزمی" href="<?php echo Pi::url($this->url('home')); ?>guide/martial-art"><i class="fa fa-angle-left"></i> مربیان و باشگاه های رزمی</a></li>
                                <li><a title="فیتنس" href="<?php echo Pi::url($this->url('home')); ?>guide/fitness"><i class="fa fa-angle-left"></i> مربیان و باشگاه های فیتنس</a></li>
                                <li><a title="راکتی" href="<?php echo Pi::url($this->url('home')); ?>guide/racquet-sports"><i class="fa fa-angle-left"></i> مربیان و باشگاه های راکتی</a></li>
                                <li><a title="اکشن" href="<?php echo Pi::url($this->url('home')); ?>guide/action"><i class="fa fa-angle-left"></i> مربیان و باشگاه های اکشن</a></li>
                                <li><a title="تمرکزی" href="<?php echo Pi::url($this->url('home')); ?>guide/concentration-sports"><i class="fa fa-angle-left"></i> مربیان و باشگاه های تمرکزی</a></li>
                                <li><a title="آبی" href="<?php echo Pi::url($this->url('home')); ?>guide/aqua-sports"><i class="fa fa-angle-left"></i> مربیان و باشگاه های آبی</a></li>
                                <li><a title="زمستانی" href="<?php echo Pi::url($this->url('home')); ?>guide/winter-sports"><i class="fa fa-angle-left"></i> مربیان و باشگاه های زمستانی</a></li>
                                <li><a title="هوای آزاد" href="<?php echo Pi::url($this->url('home')); ?>guide/outdoor-sports"><i class="fa fa-angle-left"></i> مربیان و باشگاه های هوای آزاد</a></li>
                                <li><a title="عمومی" href="<?php echo Pi::url($this->url('home')); ?>guide/general-sports"><i class="fa fa-angle-left"></i> مربیان و باشگاه های عمومی</a></li>
                            </ul>
                        </div>
                        <div class="col-xs-3">
                            <h4>ویدیو های ورزشی</h4>
                            <ul class="list-unstyled">
                                <li><a title="تیمی" href="<?php echo Pi::url($this->url('home')); ?>video/team-sports"><i class="fa fa-angle-left"></i> ویدیو های تیمی</a></li>
                                <li><a title="رزمی" href="<?php echo Pi::url($this->url('home')); ?>video/martial-art"><i class="fa fa-angle-left"></i> ویدیو های رزمی</a></li>
                                <li><a title="فیتنس" href="<?php echo Pi::url($this->url('home')); ?>video/fitness"><i class="fa fa-angle-left"></i> ویدیو های فیتنس</a></li>
                                <li><a title="راکتی" href="<?php echo Pi::url($this->url('home')); ?>video/racquet-sports"><i class="fa fa-angle-left"></i> ویدیو های راکتی</a></li>
                                <li><a title="اکشن" href="<?php echo Pi::url($this->url('home')); ?>video/action"><i class="fa fa-angle-left"></i> ویدیو های اکشن</a></li>
                                <li><a title="تمرکزی" href="<?php echo Pi::url($this->url('home')); ?>video/concentration-sports"><i class="fa fa-angle-left"></i> ویدیو های تمرکزی</a></li>
                                <li><a title="آبی" href="<?php echo Pi::url($this->url('home')); ?>video/aqua-sports"><i class="fa fa-angle-left"></i> ویدیو های آبی</a></li>
                                <li><a title="زمستانی" href="<?php echo Pi::url($this->url('home')); ?>video/winter-sports"><i class="fa fa-angle-left"></i> ویدیو های زمستانی</a></li>
                                <li><a title="هوای آزاد" href="<?php echo Pi::url($this->url('home')); ?>video/outdoor-sports"><i class="fa fa-angle-left"></i> ویدیو های هوای آزاد</a></li>
                                <li><a title="عمومی" href="<?php echo Pi::url($this->url('home')); ?>video/general-sports"><i class="fa fa-angle-left"></i> ویدیو های عمومی</a></li>
                            </ul>
                        </div>
                        <div class="col-xs-3">
                            <h4>سایر بخش های ورزشی</h4>
                            <ul class="list-unstyled">
                                <li><a title="استعدادیابی آنلاین" href="<?php echo Pi::url($this->url('home')); ?>talent"><i class="fa fa-angle-left"></i> استعدادیابی آنلاین</a></li>
                                <li><a title="مسابقات و چالش ها" href="<?php echo Pi::url($this->url('home')); ?>news/competitions-and-challenges"><i class="fa fa-angle-left"></i> مسابقات و چالش ها</a></li>
                                <li><a title="علم ورزش" href="<?php echo Pi::url($this->url('home')); ?>news"><i class="fa fa-angle-left"></i> علم ورزش</a></li>
                                <li><a title="قوانین و مقررات" href="<?php echo Pi::url($this->url('home')); ?>page/terms-and-conditions"><i class="fa fa-angle-left"></i> قوانین و مقررات</a></li>
                                <li><a title="راهنمای خرید و ارسال" href="<?php echo Pi::url($this->url('home')); ?>page/help"><i class="fa fa-angle-left"></i> راهنمای خرید و ارسال</a></li>
                                <li><a title="تبلیغات" href="<?php echo Pi::url($this->url('home')); ?>page/ads"><i class="fa fa-angle-left"></i> تبلیغات</a></li>
                                <li><a title="درباره ما" href="<?php echo Pi::url($this->url('home')); ?>page/about-us"><i class="fa fa-angle-left"></i> درباره ما</a></li>
                                <li><a title="تماس با ما" href="<?php echo Pi::url($this->url('home')); ?>contact"><i class="fa fa-angle-left"></i> تماس با ما</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="pi-footer-copyright clearfix">
        <div class="container">
            <div class="row">
                <div class="text-left col-xs-6" data-rel="license">تمام حقوق مطالب برای وب سایت <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>"><?php echo _escape($sitename); ?></a> محفوظ است.</div>
                <div class="text-right col-xs-6" data-rel="license">طراحی و توسعه <a title="فراگسترش" href="http://www.faragostaresh.com" target="_blank">فراگسترش</a></div>
            </div>
        </div>
    </div>
</footer>
<section class="pi-side-network">
    <ul>
        <li>
            <a href="https://www.instagram.com/osport.ir" title="">
                <img src="<?php echo $this->assetTheme('image/social-1.png') ?>" alt="" class="img-responsive">
            </a>
        </li>
        <li>
            <a href="https://telegram.me/osportir" title="">
                <img src="<?php echo $this->assetTheme('image/social-2.png') ?>" alt="" class="img-responsive">
            </a>
        </li>
        <li>
            <a href="https://www.linkedin.com/in/osport-ir-782588117" title="">
                <img src="<?php echo $this->assetTheme('image/social-3.png') ?>" alt="" class="img-responsive">
            </a>
        </li>
        <li>
            <a href="https://www.facebook.com/Osport-1424533724434821" title="">
                <img src="<?php echo $this->assetTheme('image/social-4.png') ?>" alt="" class="img-responsive">
            </a>
        </li>
        <li>
            <a href="http://www.aparat.com/osport.ir" title="">
                <img src="<?php echo $this->assetTheme('image/social-5.png') ?>" alt="" class="img-responsive">
            </a>
        </li>
    </ul>
</section>
</body>
</html>