<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">تیمی</h2>
    </div>
    <div class="panel-body">
        <?php echo $this->widget('video-video-new', array(
            'category'         => array(1,11, 91, 12, 13,14,15,16,17,18,19,81,92,96,101),
            'number' => '3',
            'list-type' => 'horizontal',
        )); ?>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">رزمی</h2>
    </div>
    <div class="panel-body">
        <?php echo $this->widget('video-video-new', array(
            'category'         => array(2,20,21,22,23,24,25,26,27,28,29,30,31,32,33,90),
            'number' => '3',
            'list-type' => 'horizontal',
        )); ?>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">فیتنس</h2>
    </div>
    <div class="panel-body">
        <?php echo $this->widget('video-video-new', array(
            'category'         => array(3,34,35,36,37,38,39,40),
            'number' => '3',
            'list-type' => 'horizontal',
        )); ?>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">راکتی</h2>
    </div>
    <div class="panel-body">
        <?php echo $this->widget('video-video-new', array(
            'category'         => array(4,41,42,43,44),
            'number' => '3',
            'list-type' => 'horizontal',
        )); ?>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">اکشن</h2>
    </div>
    <div class="panel-body">
        <?php echo $this->widget('video-video-new', array(
            'category'         => array(5,45,46,47,48,49,50,51,52,53,95,100),
            'number' => '3',
            'list-type' => 'horizontal',
        )); ?>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">تمرکزی</h2>
    </div>
    <div class="panel-body">
        <?php echo $this->widget('video-video-new', array(
            'category'         => array(6,54,55,56,57,58,59),
            'number' => '3',
            'list-type' => 'horizontal',
        )); ?>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">آبی</h2>
    </div>
    <div class="panel-body">
        <?php echo $this->widget('video-video-new', array(
            'category'         => array(7,60,61,62,63,64,65),
            'number' => '3',
            'list-type' => 'horizontal',
        )); ?>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">زمستانی</h2>
    </div>
    <div class="panel-body">
        <?php echo $this->widget('video-video-new', array(
            'category'         => array(8,66,67,68,69),
            'number' => '3',
            'list-type' => 'horizontal',
        )); ?>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">هوای آزاد</h2>
    </div>
    <div class="panel-body">
        <?php echo $this->widget('video-video-new', array(
            'category'         => array(9,70,71,72,73),
            'number' => '3',
            'list-type' => 'horizontal',
        )); ?>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">عمومی</h2>
    </div>
    <div class="panel-body">
        <?php echo $this->widget('video-video-new', array(
            'category'         => array(10,78,79,80,85,86,87,88,102,77,82,74,75,76,93,83,84,94),
            'number' => '3',
            'list-type' => 'horizontal',
        )); ?>
    </div>
</div>