<div class="user-bar">
    <ul class="nav navbar-nav">
        <?php if (!$block['user']['uid']) { ?>
            <li>
                <a href="<?php echo $block['user']['login']; ?>" title="<?php echo _b('Login'); ?>">
                    <?php echo _b('Login'); ?>
                </a>
            </li>
            <li>
                <a href="<?php echo $block['user']['register']; ?>" title="<?php echo _b('Register'); ?>">
                    <?php echo _b('Register'); ?>
                </a>
            </li>
        <?php } else { ?>
            <li>
                <a href="<?php echo $block['user']['profile']; ?>" title="<?php echo _escape($block['user']['name']); ?>">
                    <?php echo $block['user']['avatar']; ?>
                    <?php echo _escape($block['user']['name']); ?>
                </a>
            </li>
            <?php if (isset($block['user']['message'])) { ?>
                <li>
                    <a href="<?php echo $block['user']['message']; ?>" title="<?php echo _b('Message'); ?>">
                        <?php echo _b('Message'); ?> <span class="badge"><?php echo $block['user']['count']; ?></span>
                    </a>
                </li>
            <?php } else { ?>
                <?php if (isset($block['user']['message_url'])) { ?>
                    <li>
                        <a href="<?php echo $block['user']['message_url']; ?>" title="<?php echo _b('Message'); ?>">
                            <?php echo _b('Message'); ?> <span class="badge"><?php echo $block['user']['message_count']; ?></span>
                        </a>
                    </li>
                <?php } ?>
                <?php if (isset($block['user']['notification_url'])) { ?>
                    <li>
                        <a href="<?php echo $block['user']['notification_url']; ?>" title="<?php echo _b('Notification'); ?>">
                            <?php echo _b('Notification'); ?> <span class="badge"><?php echo $block['user']['notification_count']; ?></span>
                        </a>
                    </li>
                <?php } ?>
            <?php } ?>
            <?php if (isset($block['user']['support_url'])) { ?>
                <li>
                    <a href="<?php echo $block['user']['support_url']; ?>" title="<?php echo _b('Support'); ?>">
                        <?php echo _b('Support'); ?> <span class="badge"><?php echo $block['user']['support_count']; ?></span>
                    </a>
                </li>
            <?php } ?>
            <?php if (isset($block['user']['order'])) { ?>
                <li>
                    <a href="<?php echo $block['user']['order']; ?>" title="<?php echo _b('Follow up orders'); ?>">
                        <?php echo _b('Follow up orders'); ?>
                    </a>
                </li>
            <?php } ?>
            <?php if (isset($block['user']['credit'])) { ?>
                <li>
                    <a href="<?php echo $block['user']['credit']; ?>" title="<?php echo _b('Credit'); ?>">
                        <?php echo _b('Credit'); ?> <span class="badge"><?php echo $block['user']['amount']; ?></span>
                    </a>
                </li>
            <?php } ?>
            <li>
                <a href="<?php echo $block['user']['logout']; ?>" title="<?php echo _b('Logout'); ?>">
                    <?php echo _b('Logout'); ?>
                </a>
            </li>
        <?php } ?>
    </ul>
</div>